import 'package:flutter/material.dart';
import 'models.dart';

/// Catalogue of all generators, click upgrades, generator upgrades, and
/// achievements. Tuned to produce a long progression curve with several
/// natural prestige loops.
class GameData {
  static const List<GeneratorDef> generators = [
    GeneratorDef(
      id: 'cursor',
      name: 'Auto-палец',
      description: 'Тыкает по кругу автоматически.',
      icon: Icons.touch_app,
      color: Color(0xFF8AB4F8),
      baseCost: 15,
      baseProduction: 0.1,
    ),
    GeneratorDef(
      id: 'grandma',
      name: 'Бабуля',
      description: 'Печёт монеты, как пирожки.',
      icon: Icons.elderly_woman,
      color: Color(0xFFE8C5A0),
      baseCost: 100,
      baseProduction: 1.0,
    ),
    GeneratorDef(
      id: 'farm',
      name: 'Ферма',
      description: 'Выращивает золотую пшеницу.',
      icon: Icons.agriculture,
      color: Color(0xFF8BC34A),
      baseCost: 1100,
      baseProduction: 8.0,
    ),
    GeneratorDef(
      id: 'mine',
      name: 'Шахта',
      description: 'Добывает редкие монеты из недр.',
      icon: Icons.diamond,
      color: Color(0xFF7E57C2),
      baseCost: 12000,
      baseProduction: 47.0,
    ),
    GeneratorDef(
      id: 'factory',
      name: 'Фабрика',
      description: 'Штампует монеты на конвейере.',
      icon: Icons.factory,
      color: Color(0xFF90A4AE),
      baseCost: 130000,
      baseProduction: 260.0,
    ),
    GeneratorDef(
      id: 'bank',
      name: 'Банк',
      description: 'Делает деньги на деньгах.',
      icon: Icons.account_balance,
      color: Color(0xFFFFD54F),
      baseCost: 1400000,
      baseProduction: 1400.0,
    ),
    GeneratorDef(
      id: 'temple',
      name: 'Храм',
      description: 'Молится золотым богам.',
      icon: Icons.temple_buddhist,
      color: Color(0xFFFFA726),
      baseCost: 20000000,
      baseProduction: 7800.0,
    ),
    GeneratorDef(
      id: 'wizard',
      name: 'Башня магов',
      description: 'Превращает ману в монеты.',
      icon: Icons.auto_fix_high,
      color: Color(0xFF26A69A),
      baseCost: 330000000,
      baseProduction: 44000.0,
    ),
    GeneratorDef(
      id: 'shipment',
      name: 'Космокорабль',
      description: 'Возит монеты с других планет.',
      icon: Icons.rocket_launch,
      color: Color(0xFF42A5F5),
      baseCost: 5100000000,
      baseProduction: 260000.0,
    ),
    GeneratorDef(
      id: 'alchemy',
      name: 'Алхимическая лаборатория',
      description: 'Превращает свинец в золото.',
      icon: Icons.science,
      color: Color(0xFFEC407A),
      baseCost: 75000000000,
      baseProduction: 1600000.0,
    ),
    GeneratorDef(
      id: 'portal',
      name: 'Портал',
      description: 'Соединяет миры, полные монет.',
      icon: Icons.blur_circular,
      color: Color(0xFFAB47BC),
      baseCost: 1000000000000,
      baseProduction: 10000000.0,
    ),
    GeneratorDef(
      id: 'time_machine',
      name: 'Машина времени',
      description: 'Приносит монеты из будущего.',
      icon: Icons.access_time,
      color: Color(0xFFFF7043),
      baseCost: 14000000000000.0,
      baseProduction: 65000000.0,
    ),
    GeneratorDef(
      id: 'antimatter',
      name: 'Антиматерия',
      description: 'Конденсирует монеты из вакуума.',
      icon: Icons.brightness_7,
      color: Color(0xFF00ACC1),
      baseCost: 170000000000000.0,
      baseProduction: 430000000.0,
    ),
    GeneratorDef(
      id: 'prism',
      name: 'Призма',
      description: 'Концентрирует свет в монеты.',
      icon: Icons.change_history,
      color: Color(0xFFFFEB3B),
      baseCost: 2100000000000000.0,
      baseProduction: 2900000000.0,
    ),
    GeneratorDef(
      id: 'chancemaker',
      name: 'Махинатор удачи',
      description: 'Ловит монеты прямо из вероятностей.',
      icon: Icons.casino,
      color: Color(0xFF66BB6A),
      baseCost: 26000000000000000.0,
      baseProduction: 21000000000.0,
    ),
  ];

  static const List<UpgradeDef> clickUpgrades = [
    UpgradeDef(
      id: 'click_x2',
      name: 'Стальной палец',
      description: 'Клик ×2',
      icon: Icons.front_hand,
      kind: UpgradeKind.clickMultiplier,
      cost: 100,
      value: 2,
    ),
    UpgradeDef(
      id: 'click_x2_b',
      name: 'Перчатка силача',
      description: 'Клик ×2',
      icon: Icons.sports_mma,
      kind: UpgradeKind.clickMultiplier,
      cost: 5000,
      value: 2,
      requirement: UpgradeRequirement(minTotalClicks: 250),
    ),
    UpgradeDef(
      id: 'click_x3',
      name: 'Алмазный коготь',
      description: 'Клик ×3',
      icon: Icons.cut,
      kind: UpgradeKind.clickMultiplier,
      cost: 250000,
      value: 3,
      requirement: UpgradeRequirement(minTotalClicks: 1000),
    ),
    UpgradeDef(
      id: 'click_x5',
      name: 'Молот богов',
      description: 'Клик ×5',
      icon: Icons.flash_on,
      kind: UpgradeKind.clickMultiplier,
      cost: 50000000,
      value: 5,
      requirement: UpgradeRequirement(minTotalClicks: 5000),
    ),
    UpgradeDef(
      id: 'click_flat_10',
      name: 'Бронзовое кольцо',
      description: '+10 за клик',
      icon: Icons.circle,
      kind: UpgradeKind.clickFlat,
      cost: 1500,
      value: 10,
    ),
    UpgradeDef(
      id: 'click_flat_100',
      name: 'Серебряное кольцо',
      description: '+100 за клик',
      icon: Icons.circle_outlined,
      kind: UpgradeKind.clickFlat,
      cost: 75000,
      value: 100,
      requirement: UpgradeRequirement(minTotalEarned: 50000),
    ),
    UpgradeDef(
      id: 'click_flat_5000',
      name: 'Золотое кольцо',
      description: '+5000 за клик',
      icon: Icons.adjust,
      kind: UpgradeKind.clickFlat,
      cost: 5000000,
      value: 5000,
      requirement: UpgradeRequirement(minTotalEarned: 2000000),
    ),
    UpgradeDef(
      id: 'click_from_cps_1',
      name: 'Резонанс',
      description: 'Клик +1% от CPS',
      icon: Icons.auto_graph,
      kind: UpgradeKind.clickFromCps,
      cost: 1000000,
      value: 0.01,
      requirement: UpgradeRequirement(minTotalEarned: 500000),
    ),
    UpgradeDef(
      id: 'click_from_cps_5',
      name: 'Симбиоз',
      description: 'Клик +5% от CPS',
      icon: Icons.show_chart,
      kind: UpgradeKind.clickFromCps,
      cost: 100000000,
      value: 0.04,
      requirement: UpgradeRequirement(minTotalEarned: 50000000),
    ),
    UpgradeDef(
      id: 'click_from_cps_10',
      name: 'Гармония вселенной',
      description: 'Клик +10% от CPS',
      icon: Icons.public,
      kind: UpgradeKind.clickFromCps,
      cost: 10000000000,
      value: 0.05,
      requirement: UpgradeRequirement(minTotalEarned: 5000000000),
    ),
  ];

  /// Each generator gets three multiplicative upgrades that unlock at
  /// 10/50/100 owned. Costs are derived from generator base cost.
  static List<UpgradeDef> get generatorUpgrades {
    final list = <UpgradeDef>[];
    for (final g in generators) {
      list.addAll([
        UpgradeDef(
          id: '${g.id}_up1',
          name: '${g.name}: ускорение I',
          description: 'Производство ×2',
          icon: Icons.upgrade,
          kind: UpgradeKind.generatorMultiplier,
          cost: g.baseCost * 100,
          value: 2,
          generatorId: g.id,
          requirement: UpgradeRequirement(generatorId: g.id, minOwned: 10),
        ),
        UpgradeDef(
          id: '${g.id}_up2',
          name: '${g.name}: ускорение II',
          description: 'Производство ×2',
          icon: Icons.rocket,
          kind: UpgradeKind.generatorMultiplier,
          cost: g.baseCost * 1500,
          value: 2,
          generatorId: g.id,
          requirement: UpgradeRequirement(generatorId: g.id, minOwned: 50),
        ),
        UpgradeDef(
          id: '${g.id}_up3',
          name: '${g.name}: ускорение III',
          description: 'Производство ×2',
          icon: Icons.bolt,
          kind: UpgradeKind.generatorMultiplier,
          cost: g.baseCost * 50000,
          value: 2,
          generatorId: g.id,
          requirement: UpgradeRequirement(generatorId: g.id, minOwned: 100),
        ),
      ]);
    }
    list.addAll(const [
      UpgradeDef(
        id: 'global_x15_a',
        name: 'Логистика',
        description: 'Все генераторы ×1.5',
        icon: Icons.local_shipping,
        kind: UpgradeKind.globalMultiplier,
        cost: 100000000,
        value: 1.5,
        requirement: UpgradeRequirement(minTotalEarned: 50000000),
      ),
      UpgradeDef(
        id: 'global_x2_a',
        name: 'Глобальная экспансия',
        description: 'Все генераторы ×2',
        icon: Icons.travel_explore,
        kind: UpgradeKind.globalMultiplier,
        cost: 10000000000,
        value: 2,
        requirement: UpgradeRequirement(minTotalEarned: 5000000000),
      ),
      UpgradeDef(
        id: 'global_x2_b',
        name: 'Корпоративная синергия',
        description: 'Все генераторы ×2',
        icon: Icons.business_center,
        kind: UpgradeKind.globalMultiplier,
        cost: 1000000000000,
        value: 2,
        requirement: UpgradeRequirement(minTotalEarned: 500000000000),
      ),
      UpgradeDef(
        id: 'global_x3_a',
        name: 'Мегаструктуры',
        description: 'Все генераторы ×3',
        icon: Icons.apartment,
        kind: UpgradeKind.globalMultiplier,
        cost: 1000000000000000.0,
        value: 3,
        requirement: UpgradeRequirement(minTotalEarned: 500000000000000.0),
      ),
    ]);
    return list;
  }

  static const List<AchievementDef> achievements = [
    AchievementDef(
      id: 'first_click',
      name: 'Первый клик',
      description: 'Сделай свой первый клик.',
      icon: Icons.celebration,
      check: AchievementCheck(totalClicks: 1),
    ),
    AchievementDef(
      id: 'click_100',
      name: 'Палец чешется',
      description: '100 кликов.',
      icon: Icons.touch_app,
      check: AchievementCheck(totalClicks: 100),
    ),
    AchievementDef(
      id: 'click_1000',
      name: 'Тысяча кликов',
      description: '1 000 кликов.',
      icon: Icons.front_hand,
      check: AchievementCheck(totalClicks: 1000),
    ),
    AchievementDef(
      id: 'click_10000',
      name: 'Чемпион клика',
      description: '10 000 кликов.',
      icon: Icons.emoji_events,
      check: AchievementCheck(totalClicks: 10000),
      bonusPercent: 2.0,
    ),
    AchievementDef(
      id: 'click_100000',
      name: 'Легенда клика',
      description: '100 000 кликов.',
      icon: Icons.military_tech,
      check: AchievementCheck(totalClicks: 100000),
      bonusPercent: 5.0,
    ),
    AchievementDef(
      id: 'earn_1k',
      name: 'Первая тысяча',
      description: 'Заработай 1 000 монет.',
      icon: Icons.savings,
      check: AchievementCheck(totalEarned: 1000),
    ),
    AchievementDef(
      id: 'earn_1m',
      name: 'Миллионер',
      description: 'Заработай 1 000 000 монет.',
      icon: Icons.attach_money,
      check: AchievementCheck(totalEarned: 1000000),
      bonusPercent: 1.0,
    ),
    AchievementDef(
      id: 'earn_1b',
      name: 'Миллиардер',
      description: 'Заработай 1 000 000 000 монет.',
      icon: Icons.account_balance_wallet,
      check: AchievementCheck(totalEarned: 1000000000),
      bonusPercent: 2.0,
    ),
    AchievementDef(
      id: 'earn_1t',
      name: 'Триллионер',
      description: 'Заработай 1 триллион монет.',
      icon: Icons.workspace_premium,
      check: AchievementCheck(totalEarned: 1000000000000.0),
      bonusPercent: 3.0,
    ),
    AchievementDef(
      id: 'earn_1q',
      name: 'Квадриллион',
      description: 'Заработай 1 квадриллион монет.',
      icon: Icons.diamond,
      check: AchievementCheck(totalEarned: 1000000000000000.0),
      bonusPercent: 5.0,
    ),
    AchievementDef(
      id: 'cursor_50',
      name: 'Армия пальцев',
      description: 'Купи 50 авто-пальцев.',
      icon: Icons.touch_app,
      check: AchievementCheck(generatorId: 'cursor', generatorOwned: 50),
      bonusPercent: 1.0,
    ),
    AchievementDef(
      id: 'grandma_25',
      name: 'Семейный совет',
      description: 'Купи 25 бабуль.',
      icon: Icons.elderly_woman,
      check: AchievementCheck(generatorId: 'grandma', generatorOwned: 25),
      bonusPercent: 1.0,
    ),
    AchievementDef(
      id: 'farm_25',
      name: 'Аграрий',
      description: 'Купи 25 ферм.',
      icon: Icons.agriculture,
      check: AchievementCheck(generatorId: 'farm', generatorOwned: 25),
      bonusPercent: 1.0,
    ),
    AchievementDef(
      id: 'mine_25',
      name: 'Шахтёр',
      description: 'Купи 25 шахт.',
      icon: Icons.diamond,
      check: AchievementCheck(generatorId: 'mine', generatorOwned: 25),
      bonusPercent: 1.0,
    ),
    AchievementDef(
      id: 'all_5',
      name: 'Всего по 5',
      description: 'Купи по 5 каждого генератора.',
      icon: Icons.format_list_numbered,
      check: AchievementCheck(totalGenerators: 5),
      bonusPercent: 2.0,
    ),
    AchievementDef(
      id: 'all_25',
      name: 'Магнат',
      description: 'Купи по 25 каждого генератора.',
      icon: Icons.business,
      check: AchievementCheck(totalGenerators: 25),
      bonusPercent: 5.0,
    ),
    AchievementDef(
      id: 'cps_100',
      name: 'Поток дохода',
      description: 'Достигни 100 монет/сек.',
      icon: Icons.speed,
      check: AchievementCheck(cps: 100),
    ),
    AchievementDef(
      id: 'cps_1m',
      name: 'Лавина',
      description: 'Достигни 1М монет/сек.',
      icon: Icons.waves,
      check: AchievementCheck(cps: 1000000),
      bonusPercent: 3.0,
    ),
    AchievementDef(
      id: 'prestige_1',
      name: 'Новое начало',
      description: 'Соверши первое перерождение.',
      icon: Icons.refresh,
      check: AchievementCheck(prestigeLevel: 1),
      bonusPercent: 1.0,
    ),
    AchievementDef(
      id: 'prestige_5',
      name: 'Многократное возрождение',
      description: 'Соверши 5 перерождений.',
      icon: Icons.all_inclusive,
      check: AchievementCheck(prestigeLevel: 5),
      bonusPercent: 5.0,
    ),
    AchievementDef(
      id: 'prestige_25',
      name: 'Бессмертие',
      description: 'Соверши 25 перерождений.',
      icon: Icons.auto_awesome,
      check: AchievementCheck(prestigeLevel: 25),
      bonusPercent: 10.0,
    ),
  ];
}
