"""Character classes (RPG jobs)."""
from __future__ import annotations
from .stats import Stats, Resists


CLASSES = {
    "Warrior": {
        "desc": "Heavy armor, strong arms. Cleave, shield bash.",
        "stat_bonus": Stats(STR=3, CON=2),
        "hp_per_level": 8,
        "mp_per_level": 1,
        "starting_items": ["longsword", "wooden_shield", "leather_armor",
                           "potion_minor_healing", "potion_minor_healing", "ration"],
        "starting_skills": ["weapon_sword", "shield", "athletics"],
        "starting_spells": [],
        "abilities": ["cleave", "shield_bash", "second_wind", "rally"],
        "primary": "STR",
    },
    "Paladin": {
        "desc": "Holy warrior. Smite, lay on hands, divine aura.",
        "stat_bonus": Stats(STR=2, CON=2, CHA=1, WIS=1),
        "hp_per_level": 7,
        "mp_per_level": 3,
        "starting_items": ["mace", "wooden_shield", "scale_mail",
                           "potion_minor_healing", "ration", "holy_symbol"],
        "starting_skills": ["weapon_blunt", "shield", "holy"],
        "starting_spells": ["smite", "heal_self_minor", "bless", "cure_disease"],
        "abilities": ["lay_hands", "divine_aura", "smite_evil", "turn_undead"],
        "primary": "STR",
    },
    "Mage": {
        "desc": "Elemental sorcerer. Fire, frost, lightning.",
        "stat_bonus": Stats(INT=4, WIS=1),
        "hp_per_level": 4,
        "mp_per_level": 6,
        "starting_items": ["staff", "robe", "potion_minor_mana",
                           "potion_minor_mana", "ration", "spellbook_basic"],
        "starting_skills": ["evocation", "concentration"],
        "starting_spells": ["magic_missile", "ignite", "shield_arcane",
                            "frost_ray", "spark"],
        "abilities": ["arcane_focus"],
        "primary": "INT",
    },
    "Wizard": {
        "desc": "Scholar of all schools. More spells, less power.",
        "stat_bonus": Stats(INT=4, WIS=2),
        "hp_per_level": 4,
        "mp_per_level": 7,
        "starting_items": ["dagger", "robe", "potion_minor_mana",
                           "scroll_identify", "scroll_magic_mapping", "ration",
                           "spellbook_basic"],
        "starting_skills": ["evocation", "abjuration", "divination"],
        "starting_spells": ["magic_missile", "detect_magic", "identify",
                            "shield_arcane", "magic_mapping"],
        "abilities": ["spell_research"],
        "primary": "INT",
    },
    "Rogue": {
        "desc": "Stealth, traps, backstab, lockpicking.",
        "stat_bonus": Stats(DEX=4, LUCK=2),
        "hp_per_level": 5,
        "mp_per_level": 2,
        "starting_items": ["short_sword", "leather_armor", "lockpick",
                           "lockpick", "smoke_bomb", "potion_minor_healing",
                           "ration", "throwing_knife", "throwing_knife",
                           "throwing_knife"],
        "starting_skills": ["weapon_dagger", "stealth", "lockpick", "trapping"],
        "starting_spells": [],
        "abilities": ["backstab", "vanish", "shadow_step", "evasion"],
        "primary": "DEX",
    },
    "Ranger": {
        "desc": "Bow master. Tracking. Animal companion.",
        "stat_bonus": Stats(DEX=3, WIS=2, CON=1),
        "hp_per_level": 6,
        "mp_per_level": 3,
        "starting_items": ["bow", "arrow_bundle", "leather_armor",
                           "potion_minor_healing", "ration"],
        "starting_skills": ["weapon_bow", "tracking", "nature"],
        "starting_spells": ["hunter_mark", "barkskin"],
        "abilities": ["called_shot", "summon_companion", "trap_arrow"],
        "primary": "DEX",
    },
    "Priest": {
        "desc": "Healer and turner of undead.",
        "stat_bonus": Stats(WIS=4, CHA=2),
        "hp_per_level": 5,
        "mp_per_level": 5,
        "starting_items": ["mace", "scale_mail", "holy_symbol",
                           "potion_minor_healing", "potion_minor_healing",
                           "ration"],
        "starting_skills": ["weapon_blunt", "holy", "healing"],
        "starting_spells": ["heal_self_minor", "heal_minor", "bless",
                            "smite", "cure_poison"],
        "abilities": ["channel_divinity", "turn_undead"],
        "primary": "WIS",
    },
    "Druid": {
        "desc": "Nature, shapeshift, summon beasts.",
        "stat_bonus": Stats(WIS=4, CON=2),
        "hp_per_level": 5,
        "mp_per_level": 5,
        "starting_items": ["club", "leather_armor", "ration",
                           "potion_minor_healing"],
        "starting_skills": ["weapon_blunt", "nature", "shapeshift"],
        "starting_spells": ["entangle", "barkskin", "summon_wolf",
                            "thorn_whip", "regrowth"],
        "abilities": ["wild_shape_wolf", "wild_shape_bear", "wild_shape_eagle"],
        "primary": "WIS",
    },
    "Necromancer": {
        "desc": "Master of death. Summons undead, drains life.",
        "stat_bonus": Stats(INT=4, CON=2),
        "hp_per_level": 5,
        "mp_per_level": 6,
        "starting_items": ["dagger", "robe", "ration",
                           "potion_minor_mana", "scroll_summon_skeleton"],
        "starting_skills": ["necromancy", "concentration"],
        "starting_spells": ["bone_dart", "drain_life", "raise_skeleton",
                            "fear", "shadow_bolt"],
        "abilities": ["soul_harvest", "death_pact"],
        "primary": "INT",
    },
    "Monk": {
        "desc": "Martial artist. Chi powers, no armor.",
        "stat_bonus": Stats(DEX=3, WIS=3),
        "hp_per_level": 6,
        "mp_per_level": 3,
        "starting_items": ["staff", "ration", "ration",
                           "potion_minor_healing"],
        "starting_skills": ["weapon_unarmed", "weapon_staff", "athletics",
                            "concentration"],
        "starting_spells": [],
        "abilities": ["flurry", "stunning_strike", "deflect", "wholeness"],
        "primary": "DEX",
    },
    "Berserker": {
        "desc": "Rage-fueled killer. The angrier, the deadlier.",
        "stat_bonus": Stats(STR=4, CON=3, INT=-1),
        "hp_per_level": 9,
        "mp_per_level": 1,
        "starting_items": ["greatsword", "leather_armor",
                           "potion_minor_healing", "potion_minor_healing",
                           "ration"],
        "starting_skills": ["weapon_axe", "weapon_sword", "athletics"],
        "starting_spells": [],
        "abilities": ["rage", "reckless", "blood_frenzy", "intimidate"],
        "primary": "STR",
    },
    "Bard": {
        "desc": "Songs that buff, debuff and amaze.",
        "stat_bonus": Stats(CHA=4, DEX=2, INT=1),
        "hp_per_level": 5,
        "mp_per_level": 4,
        "starting_items": ["rapier", "leather_armor", "lute",
                           "potion_minor_healing", "ration"],
        "starting_skills": ["weapon_dagger", "performance", "lore"],
        "starting_spells": ["song_courage", "vicious_mockery", "charm",
                            "minor_illusion", "healing_word"],
        "abilities": ["jack_of_all_trades"],
        "primary": "CHA",
    },
    "Alchemist": {
        "desc": "Brews potions, throws bombs, drinks anything.",
        "stat_bonus": Stats(INT=3, DEX=2, CON=1),
        "hp_per_level": 5,
        "mp_per_level": 4,
        "starting_items": ["dagger", "leather_armor", "potion_minor_healing",
                           "potion_minor_mana", "alchemy_kit", "ration",
                           "ration", "bomb_fire", "bomb_fire"],
        "starting_skills": ["alchemy", "weapon_dagger"],
        "starting_spells": [],
        "abilities": ["mutagen", "throw_bomb"],
        "primary": "INT",
    },
}


def class_keys():
    return list(CLASSES.keys())
